name: First Worfklow
on: [push]

jobs: 
  run-shell-commands:
    runs-on: ubuntu-latest
    steps: 
    - name: echo a string
      run: echo "Helloo----"
    - name: Multiline commands 
      run: |
        node -v 
        npm -v 